title:<p align="center"> Gagan Dhal</p>
logo: /assets/img/1609783158745.jpg


description: 
  <p align="center" >
  <a href="https://www.linkedin.com/in/gagan-dhal-64108768/">LinkedIn</a> |
  <a href="https://github.com/gdhal09">GitHub</a>

  <br>
  I am working as a Data Analyst
  
  <br>
  </p>
  

theme: jekyll-theme-minimal
