title: <p align="center"> Gagan Dhal</p>
logo: /assets/img/1609783158745.jpg


description: 
  <p align="center" >
  <a href="https://drive.google.com/file/d/1ntAalbbQj7CbIyJO9OQPjZUlKysz_Ck5/view?usp=share_link">Resume</a> |
  <a href="https://www.linkedin.com/in/gagan-dhal-64108768/">LinkedIn</a> |
  <a href="https://github.com/gdhal09">GitHub</a>

  <br>
  Physics graduate with a decade worth of experience in R&D and Biotechnology. Currently pursuing PG degree in Data Science from IIIT-Bangalore.
  Interest in application of ML/AI to provide cutting-edge solutions in the field of Heathcare and Biotechnology.

  
  
  
  
  
  
  
  
  
  
  <br>
  </p>
  

theme: jekyll-theme-minimal
